### ISSUE TITLE
Expanding the interface

### ISSUE THREAD

**Issue by assertchris** [mnapoli/BlackBox#12]
Whichever storage interface(s) we end up having; I think it might be good to add:

- `push`
- `pop`
- `shift`
- `unshift` 

...to deal with key-less values. 

**Edit**

Sure, folks can just use `$storage = new SomeStorage(array_push(iterator_to_array($storage), $item));` but that seems cumbersome. :)

**Comment by sagikazarmark** [comment]
This is something that makes sense in case of a Queue (and actually is part of SplQueue), but I can't see a use case for data storage. My problem with it is that all data from real key-value based backends (memcached, redis) must be loaded to provide such a functionality.

**Comment by assertchris** [comment]
It's not about which backend is being used, it's about whether the items are keyed or not. Memcached, for example, doesn't provide a way to return all stored keys, which means we need to maintain a meta key/value which lists all the stored keys. That is ordered, so popping is done by getting the meta key/value and removing/returning the top item from cache.

**Comment by mnapoli** [comment]
Honestly for backends such as Memcached that do not allow iteration, I would suggest not supporting them at all. After all, the only use case of Memcached is for very dumb (and fast) caching, it's not really meant for anything else. This library is meant to be a storage, if Memcached isn't compatible then be it.

I don't have a strong stance on this, but yeah having fewer very strong/robust implementations is better than trying to support everything "okayish" IMO. The fake keys with Memcached could introduce overhead, potential keys conflicts (what if people store something under the key `keys`), potential race conditions, …

Back to the original topic, there should indeed be a way to "add" and "remove" elements. We could keep using `set()` like this:

```php
// explicit key
$storage->set('mnapoli', new User(...));

// autogenerated key if null is given
$key = $storage->set(null, new User(...));
```

Alternatively, we could add a `add()` method to be more explicit:

```php
// explicit key
$storage->set('mnapoli', new User(...));

// autogenerated key if null is given
$key = $storage->add(new User(...));
```

The thing though is that `push()` and other similar methods don't make sense on a key-value storage because there is no order, no beginning and no end.

Regarding removing items, today this is how you do it:

```php
$storage->set('foo', null);
```

We could add a `remove($key)` method though.

**Comment by sagikazarmark** [comment]
+1 for adding more methods to have a decent domain.

I am not sure if iteration is really needed.  As you said, this wants to be about storage and not a query builder for a storage. So I am not sure if more functionality is needed than key-based actions. What do you think? Can you give me some examples?

I think this and the library scope issue are getting to be the same.

**Comment by mnapoli** [comment]
At first I didn't have the iteration but it turned out to be essential (at least in my own use cases). E.g. say you store a list of "projects", at some point you will need to display the list.

In http://isitmaintained.com I want to display the latest repositories analyzed. And I also need to iterate the list to refresh the stats (in a cron job).

Anyway when you use a DB table, the main operations are: getting one item by ID or displaying the list.

**Comment by sagikazarmark** [comment]
Ok, so we have to basic feature set to support:

- key based operations
- list based operations

When I say list based operations I mean more than returning the list: return one item, etc. Anything that makes sense.

I still feel that both can live together in one package:

- `MapStorage`
- `IterableStorage`

Nothing holds you from implementing both. However this can be a limitation of the backend and nothing should force you to drop one if you can't have both.

This could probably make the library even more powerful, as the ones who look for a simple key-value storage lib still can use it.

**Comment by sagikazarmark** [comment]
@mnapoli What do you think about this? Also, by removing `Storage` I think `MapAdapter` should go as well.

**Comment by mnapoli** [comment]
I'm not sure I see a point of having a key-value store without being able to list entries. Storing is about saving data and retrieving it later. If you can't retrieve the list, then that list has to be stored elsewhere (else you are losing data). Keys can be saved by the end users (URL bookmarks, or their emails, or their username, …) but the whole list, I don't think so.

Key access only sounds a lot like caching to me and there are already a good bunch of libraries doing that. Are there a lot of storage backends that do not allow iterating? I only see caching backends, e.g. Memcached, and caching backends are not storage backends (unless they are not only about caching, like Redis).

**Comment by sagikazarmark** [comment]
What I am pointing is to have a few interfaces which we can cover all possible use cases/backends with. You can have a prefered, robust API (building up from several segments/interfaces), but it would be better to let the decision to the developer whether he/she needs it or not. By letting backend limitations to have affect on the implemented interfaces we also provide a classification of different storage backends, so that it is clear that which backend can serve which purpose. Which returns to the idea to let the developer choose based on his/her needs.

**Comment by mnapoli** [comment]
I understand, let the user choose what he needs.

But in that case why not separating `get` and `set` in separate interfaces if some users want to use a read-only storage (-> which wouldn't be a storage anymore).

My point is that when people need key-value storage, what do they actually need? IMO it's a cache, but maybe I'm wrong just tell me use cases. Plenty of existing libraries cover the key-values use case, most of them are caches. There's no point in implementing that again just because we can. I think we should provide a storage abstraction that fills a user need, and forget about other needs if they are already implemented and if they are not about storage.

So ISP is good, but in that case splitting what makes the essence of a storage into interfaces that are not about storage anymore is going to far and is deserving the purpose of that library.

Of course the hard part is defining what would be the essence of a simple yet usable storage API ;)
(and again, to me, get()/set() is not a real storage because data would be lost by not being able to retrieve it)

**Comment by sagikazarmark** [comment]
A valid usecase for simple get/set is a session implementation. That could rely on an interface which supports get/set/delete operations. IMO Memcached is totally fine for session backend. Also, caching is a higher level thing. IMO it also relies on storage, which makes it a lower level thing.

We agree in that we should provide an abstraction to fill the user's needs. But that requires to have multiple interfaces, with separated concerns. Again, the aim is not to reimplement caching libraries, but have the possibility to do it with a decent interface. I am not even talking about implementations, but generic segments of storage. And yeah, we should at least take a look at the existing implementations, backends to see what's happening out there. Who knows, one day probably blackbox will be the storage under several caching libraries.

**Comment by mnapoli** [comment]
Ah I now see thanks for your patience to explain ;) I didn't have a so much lower-level vision, in my head it was rather higher level: fill one specific need of a simple storage API in-between basic caching stuff/file_get_contents and ORMs (meant for end users). I didn't imagine it as a base building block to abstract any storage.

I'll get back to you soon about this, I'm working right now ;)

**Comment by sagikazarmark** [comment]
Take your time. ;)

**Comment by mnapoli** [comment]
Back from holidays!

So I took some time to think about all this and here is my POV: I want to build a storage library that is midway between a full-fledged ORM (e.g. Doctrine) and a Cache/Simple storage (e.g. get/set).

Why? I repeatedly find myself needing to store objects in small apps and I always have to bring the big guns (e.g. Doctrine). If I don't, I end up limited with a simple cache or key-value API after some time. I want a storage to replace ORMs for simpler needs: one that's super easy to use, that provides 80% of the features you'd expect from a storage and that can help me to scale (i.e. switching implementations easily).

An example that happened yet again today: I had to setup & use Doctrine ODM just to store 1 kind of objects in MongoDB… I wish there was something simpler.

I don't want to implement a key-value store again because there are already many of them. Take the last one I linked to: https://github.com/webmozart/key-value-store It look quite fine. But key-value only covers maybe 50% of the API we need when we need a simple storage, I know it's not enough for my use cases.

I think this package, in order to be useful, should not try to address everything. Want key-value abstraction: there are already plenty. If this package was to reimplement it again, it would be a waste of time and energy, and it would distract from the problem it is trying to solve.

> A valid usecase for simple get/set is a session implementation.

That's a good example, and this can be done with plenty of other libraries. So I think it's a matter of choosing not to care for these use cases.

Again, I think there's value in addressing something that doesn't really exist today: a simpler alternative to ORMs that could work with many backend.

About this:

> Again, the aim is not to reimplement caching libraries, but have the possibility to do it with a decent interface.

I don't think it's a good thing to build a caching library on top of another abstraction. Caching backends are usually so simple that the additional overhead is really not worth it. All Doctrine Cache implementations are very simple.

> We agree in that we should provide an abstraction to fill the user's needs. But that requires to have multiple interfaces, with separated concerns.

So to answer this I think this lib should address one single concern (a simple storage). Key-value store is another concern and doesn't need to be solved here (since it's already solved elsewhere).

So what I'm planning to do:

- try to define a `StorageInterface` which covers most common use cases for a collection storage (e.g. how we usually use a database, because the point is to replace ORMs)
- keep the number of implementations realistic: if nobody uses and maintains implementation X, there is no reason it should exist. File + Redis + Db sounds like a good start.
- I'd like to introduce in the future a way to query storages (very simple stuff): for storage that don't support that (e.g. array, file, …) the query will be executed in PHP just like Doctrine's Criterias

I get that it's probably not what you guys had in mind, and to be honest that's not especially what I had in mind when I first started this project. I wanted to address many problems at once, with the idea of abstracting many use cases and potentially standardizing things. But that's shooting too far, where often there are already existing solutions. **I'd rather focus on solving *one* problem and solving it good**. And I also realize I have nowhere near the time, knowledge and energy to try standardizing storage interfaces… This is just too big.

I hope that you guys will be fine with this even if it means we can't merge all our ideas and projects together because maybe you have other goals!

**Comment by sagikazarmark** [comment]
Well, I am fine with that. It was never the problem for me to implement
something like this, but to shoot further. ;)

Anyway, we don't agree in that there are many AND great key-value
libraries, because there are not really. At least I have some issues with
them. But there is always room for improvement.

**Comment by assertchris** [comment]
Seems the direction has changed a little, and in respect to that I am closing this. Thanks for the discussion!

**Comment by mnapoli** [comment]
@sagikazarmark By the way I just saw that they are discussing a key-value storage interface at the FIG. So that's a good thing, maybe yet another reason to try to duplicate that effort here? I'm not against having another round at that topic when we get the main thing more stabilized in a few weeks. Maybe we'll find it's actually a very good idea to try to cover it here. In the meantime, personally, I want to focus on making that storage thing usable (I have some use cases I want to fill ;)

**Comment by sagikazarmark** [comment]
@mnapoli I am fine with all these things. I see the need for such a storage implementation as well. However I am not entirely sure that putting it into the FIG's hands is the best idea. Nothing personal, but I don't really like how they do things: someone pops in and changes the whole thing. Looking at the two implementations (https://github.com/webmozart/key-value-store, https://github.com/adammbalogh/key-value-store) the latter is clearly a better abstraction. However the implementation is not. I already contacted the author to ask about his plans.

If we are going to make this a high-level storage library, I don't think mixing key-value storage in is a good idea. However if we can make it a more generalized library, that would be awesome as well. But you specifically said you didn't want that.

**Comment by mnapoli** [comment]
> However if we can make it a more generalized library, that would be awesome as well. But you specifically said you didn't want that.

Well it's not that I'm against it per se, but I'd rather make something directly useful first and then if something better can come out of it why not.

As you can see [in the releases](https://github.com/mnapoli/BlackBox/releases) I've done 6 iterations of different interfaces yet, everything is still unstable and being able to move fast is quite appreciable. Shooting in many direction and trying to come up with universal/generic solutions is no longer a priority for me, especially since it takes so much time and energy, and it slows down the stuff that is useful immediately. And smarter people are already at it :)

Who knows maybe we'll make `BlackBox Storage` and `BlackBox KeyValueStore` in the future, but right now I want to focus on definitely useful and new "storage" thing and not get lost in too many goals.

**Comment by mnapoli** [comment]
I've merged the interfaces in one for now, I've pushed to master.

I'll be opening several issues for smaller topics.
