### ISSUE TITLE
Proposal: Cache backends with Doctrine\Cache

### ISSUE THREAD

**Issue by assertchris** [mnapoli/BlackBox#5]
Could introduce many MapStorage backends using Doctrine\Cache. If you're keen, perhaps I could submit a PR?

I would love to build messengers (in [revolvephp/assistant](https://github.com/revolvephp/assistant)) off of this.

**Comment by mnapoli** [comment]
Definitely keen, but I think I didn't do that because they are not iterable/we can't get all the items of a cache. I guess that's because some caches don't support these kind of operations, like Memcached IIRC.

So I'm afraid they need to be reimplemented here like for Redis :/

**Comment by assertchris** [comment]
This is how I got around that, with Memcached: https://github.com/revolvephp/assistant/blob/master/src/Messenger/CacheMessenger.php#L105-L114

**Comment by mnapoli** [comment]
True that could work! OK then

By the way if you want to use it "seriously" (until now I'm only using it in https://github.com/mnapoli/IsItMaintained) we could move it to an org too (BlackBox, the league, …).

**Comment by assertchris** [comment]
Wasn't sure if you'd be keen for the league, but that would be the best place for it in terms of adoption. Let's give it a go! :)

**Comment by mnapoli** [comment]
That was one of my new year resolution: start contributing there ;)

The only downside I see with this is that, *ideally*, this package should only ship the interfaces and a few generic adapters. Then all other adapters (Doctrine Cache, Dbal, Flysystem, …) should be each a separate package so that we can have explicit Composer `require`, and version constraints… (http://php-and-symfony.matthiasnoback.nl/2014/04/theres-no-such-thing-as-an-optional-dependency/ or his book talks about it too, very interesting)

So ~10 packages in the League organization would be messy…

But I guess that's just a technical issue that can be solved, I am definitely in favor of proposing the project there.

**Comment by assertchris** [comment]
https://github.com/thephpleague?query=omnipay ^^

**Comment by sagikazarmark** [comment]
@mnapoli same feelings about deparating backends.

**Comment by sagikazarmark** [comment]
As for the caching: I am not sure it makes much sense. For caching you would probably use the same backends that you use for storage: Redis, Memcached, etc. Probably APC the only one which you wouldn't. Also, adding the overhead of writting data to cache/invalidating data does not worth it in a data storage implementation.

**Comment by sagikazarmark** [comment]
Did I misunderstand this: do you want to cache data or just use the backends provided by Doctrine Cache?

**Comment by assertchris** [comment]
Just the backends. :)

**Comment by sagikazarmark** [comment]
Ah, I see. Well, I am not sure about that either. It is an extra dependency. And probably not a clear case of DRY.

**Comment by mnapoli** [comment]
If we have a look at the implementations of Doctrine Cache:

- APC
- Couchbase
- ~~File & Filesystem & PhpFile~~ (we have this)
- Memcached
- ~~Redis~~ (we have this)
- Riak
- Wincache
- Xcache
- ZendData

These Doctrine implementations are trivial, which means it would indeed make more sense to reimplement them here rather than go through another Composer dependency and Doctrine layer. Also Doctrine Caches are not iterable, and we want these kind of features. Finally the implementation trick needed to remember keys (e.g. store a keys array inside the cache) is really not optimal.

So considering this, I would also be +1 to reimplement those, or at least the most popular ones (e.g. who needs Riak, or Wincache :p).

**Comment by assertchris** [comment]
Re-implementing the simple providers does seem like a better idea. Let's do that where needed/makes sense!
