### ISSUE TITLE
Proposal: MQ backends

### ISSUE THREAD

**Issue by assertchris** [mnapoli/BlackBox#6]
Could make a few `Storage` backends with message queues.

**Comment by mnapoli** [comment]
Yep! But would the be implementing `Storage`, `MapStorage` or a new interface?

**Comment by assertchris** [comment]
They're not keyed in all the queues IIRC. `I think Storage`...

**Comment by mnapoli** [comment]
OK I wasn't sure, but you are definitely welcome!

**Comment by assertchris** [comment]
Seems like we might need a queue abstraction layer for this to be a thing.Thinking about creating a framework-agnostic version of https://github.com/illuminate/queue.

**Comment by sagikazarmark** [comment]
@assertchris check [bernardphp](http://bernardphp.com). I also maintained my own queue abstraction, and ended up having the same interface as bernard. I don't think creating a new abstraction makes much sense. Just my two cents.

As for this issue: What is the point of having a Queue storage? I mean using a service for something which is out of scope... is it a good idea? Queues are what the name says: queue data. Obviously it stores data, but the point is the order and the destination of the data

**Comment by mnapoli** [comment]
I'm +1 on focusing on storage library, queues are well handled by a load of existing solutions. If we are talking about "Queue storage", then I'd love to know how it would be used/use cases. That's why I wanted to know if it would be implementing `MapStorage`: I'm not sure if it's worth creating a different storage type. But maybe that's already what you have in mind judging on #10

**Comment by assertchris** [comment]
Looks like queues won't make the release version.
